// Canonical Supabase client import for the app
// Note: In Lovable frontend apps, env vars are not used directly.
// We re-export the single client instance generated by the Supabase integration.

export { supabase } from "@/integrations/supabase/client";
export type { Database } from "@/integrations/supabase/types";
