// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byzjesxixjztsjhxwgic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5emplc3hpeGp6dHNqaHh3Z2ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjYwMDksImV4cCI6MjA3MDM0MjAwOX0.QKtBL4mrugPqDR1VBMWLZrSRTxXiSHrva2lnl1zQ6kw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});